# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.define "nfs_server" do |nfss|
    #nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
	nfss.vm.network "private_network", ip: "192.168.50.10"
    nfss.vm.hostname = "nfss"
    nfss.vm.provision "shell", path: "nfs_server.sh"
  end

  config.vm.define "nfs_client" do |nfsc|
    #nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
	nfsc.vm.network "private_network", ip: "192.168.50.11"
    nfsc.vm.hostname = "nfsc"
    nfsc.vm.provision "shell", path: "nfs_client.sh"
  end


end
