---
# tasks file for client

- name: Check that the somefile.conf exists
  ansible.builtin.stat:
     path: ~/.ssh/id_rsa
  register: stat_result

- name: Create key
  ansible.builtin.user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: stat_result.stat.exists==false

- name: Install sshpass
  package:
    name: sshpass
    state: present

- name: Copy ssh key to borg server
  command: sshpass -ppass ssh-copy-id -o StrictHostKeyChecking=no borguser@192.168.1.201
  become: yes
  when: stat_result.stat.exists==false

- name:     Create /var/backup
  file:     name=/var/backup state=directory

- name:     Check repository
  stat:     path=/var/backup/repo.flg
  register: repo

- file:     path=/var/backup/repo.flg state=touch
  when:     repo.stat.exists==false

- name:     Create repository
  command:  borg init -e none borguser@192.168.1.201:/var/backup/{{ inventory_hostname }}
  when:     repo.stat.exists==false

- name:     Copy backup script
  template:
    src:    backup.sh
    dest:   /opt/backup.sh
    mode:   0755

- name:     Add cron job for backup script
  cron:
    name:   5min-backup
    hour:   "*"
    minute: "*/5"
    job:    /opt/backup.sh
    user:   root