# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  #config.ssh.insert_key = false
  config.vm.box = "centos/7"
  
 # config.vm.provider "virtualbox" do |vb|
 #   # Display the VirtualBox GUI when booting the machine
 #   vb.gui = true
 #
 #   # Customize the amount of memory on the VM:
 #     vb.memory = "1024"
 #     vb.cpus = 2
 # end
  
  
  # Ansible guests
  #======================================
  config.vm.define "sys" do |machine|
    machine.vm.network "public_network", ip: "192.168.1.201"
    machine.vm.hostname = "sys"
    machine.vm.provider "virtualbox" do |vb|
	vb.memory = "2048"
	vb.cpus = 2
    end
    machine.vm.provision "shell", inline: <<-SHELL
      yum update -y
      yum install -y httpd mc
      cp /vagrant/mylog.conf /etc/sysconfig/
      cp /vagrant/mylog.log /var/log/
      cp /vagrant/eye.sh /opt/
      cp /vagrant/mylog.service /vagrant/mylog.timer /etc/systemd/system/
      systemctl daemon-reload
      systemctl start mylog.service
      systemctl enable mylog.service
    SHELL
  end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
