---
# tasks file for server
- name: Create a new ext4 primary partition
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: present

- name: Create a ext4 filesystem on /dev/sdb1
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb1
    state: present

- name: Add the user borguser
  ansible.builtin.user:
    name: borguser
    comment: borg backup user
    password: "{{ 'pass' | password_hash('sha512') }}"

- name: Create a directory for backup
  ansible.builtin.file:
    path: /var/backup
    state: directory
    mode: '0755'

- name: Mount backup disk
  ansible.posix.mount:
    path: /var/backup
    src: /dev/sdb1
    fstype: ext4
    opts: nodev
    state: mounted

- name: borguser folder owner
  ansible.builtin.file:
    path: /var/backup
    owner: borguser
    group: borguser




