---
# tasks file for nginx-test
# enable EPEL repo by installing the epel-release package
- name: install EPEL repo
  become: yes
  yum: name=epel-release state=present

- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx restart

- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx restart

- name: Replace nginx.conf
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
        - nginx restart

- name: Index page
  template:
    src: templates/index.html
    dest: /usr/share/nginx/html/index.html
