---
- name: au
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.auditd
      auditd_local_events: "no"
      auditd_rules:
        - file: /var/log/audit/
          keyname: auditlog
        - file: /etc/audit/
          permissions:
            - write
            - attribute_change
          keyname: auditconfig